### ISSUE TITLE
Action Failing

### ISSUE THREAD

**Issue by jacobblyons** [kuler90/activate-unity#3] opened 2021-05-06 15:51 UTC
Hello. 

This action has worked great for me in the past, but it recently stopped working. 

my workflow:
```
- name: Setup Unity
  uses: kuler90/setup-unity@v1.0.6
  with:
    unity-version: 2020.2.2f1
    unity-modules: 
      mac-il2cpp
      windows-il2cpp
      ios
      android
      
- name: Activate Unity
  uses: kuler90/activate-unity@v1
  with:
    unity-username: ${{ secrets.UNITY_USERNAME }}
    unity-password: ${{ secrets.UNITY_PASSWORD }}
```
the error:

```
/Applications/Unity/Hub/Editor/2020.2.2f1/Unity.app/Contents/MacOS/Unity -batchmode -nographics -quit -logFile - -createManualActivationFile
[Licensing::Module] Channel doesn't exist: "LicenseClient-runner"
Launching external process: /Applications/Unity/Hub/Editor/2020.2.2f1/Unity.app/Contents/Frameworks/UnityLicensingClient.app/Contents/Resources/Unity.Licensing.Client
[Licensing::Module] Successfully launched the LicensingClient (PId: 1771)
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-runner" (connect: 0.70s, validation: 0.07s, handshake: 0.30s)
[Licensing::Module] Connected to LicensingClient (PId: 1771, launch time: 0.00, total connection time: 1.07s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully

 Generating manual activation license file.

LICENSE SYSTEM [202156 5:26:40] License activate file written to: Unity_v2020.2.2f1.alf

 Manual activation license file saved.
Error: Navigation timeout of 30000 ms exceeded
```

Any help would be greatly appreciated.

Thanks!

**Comment by kuler90** [comment] 2021-05-06 16:03
Hi @jacobblyons,

I don't see `unity-authenticator-key` in your workflow.

**Comment by jacobblyons** [comment] 2021-05-07 04:48
interesting.. I didn't use `unity-authenticator-key` in my previous project. I will set it up and see if that helps.

**Comment by jacobblyons** [comment] 2021-05-07 05:21
@kuler90 - I added `unity-authenticator-key` but received the same error.

**Comment by blockcarl** [comment] 2021-05-12 18:21
Having the same issue, it worked fine on my last build 20 days ago and stopped working today. I added the `unity-authenticator-key` but it didn't seem to fix.

I got the following error before the timeout as well:

```<!DOCTYPE html>
<html>
  <head>
    <title>Error - 500</title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <style>
      body {
        padding: 50px 80px;
        font: 14px "Helvetica Neue", Helvetica, sans-serif;
      }
      h1 {
        font-size: 2em;
        margin-bottom: 5px;
      }
      pre {
        font-size: .8em;
      }
    </style>
  </head>
  <body>
    <div id="error">
      <h1>Error</h1>
    <p>Looks like something broke!</p>
      <pre>
        <code>
TypeError: Cannot read property &#39;sessionState&#39; of undefined
    at _callee$ (/var/silkcloud/genesis-activation-ui/backend/lib/request.js:28:39)
    at tryCatch (/var/silkcloud/genesis-activation-ui/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/var/silkcloud/genesis-activation-ui/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.&lt;computed&gt; [as next] (/var/silkcloud/genesis-activation-ui/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/var/silkcloud/genesis-activation-ui/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /var/silkcloud/genesis-activation-ui/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (&lt;anonymous&gt;)
    at new F (/var/silkcloud/genesis-activation-ui/node_modules/core-js/library/modules/_export.js:36:28)
    at /var/silkcloud/genesis-activation-ui/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at getOAuthToken (/var/silkcloud/genesis-activation-ui/backend/lib/request.js:13:1)
    at _callee2$ (/var/silkcloud/genesis-activation-ui/backend/lib/request.js:54:18)
    at tryCatch (/var/silkcloud/genesis-activation-ui/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/var/silkcloud/genesis-activation-ui/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.&lt;computed&gt; [as next] (/var/silkcloud/genesis-activation-ui/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/var/silkcloud/genesis-activation-ui/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /var/silkcloud/genesis-activation-ui/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
        </code>
      </pre>
    </div>
  </body>
</html>
<!DOCTYPE html>
<html>
  <head>
    <title>Error - 400</title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <style>
      body {
        padding: 50px 80px;
        font: 14px "Helvetica Neue", Helvetica, sans-serif;
      }
      h1 {
        font-size: 2em;
        margin-bottom: 5px;
      }
      pre {
        font-size: .8em;
      }
    </style>
  </head>
  <body>
    <div id="error">
      <h1>Error</h1>
    <p>Looks like something broke!</p>
      <pre>
        <code>
Error: Unencoded &lt;
Line: 0
Column: 2
Char: 
    at error (/var/silkcloud/genesis-activation-ui/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/var/silkcloud/genesis-activation-ui/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/var/silkcloud/genesis-activation-ui/node_modules/sax/lib/sax.js:1080:13)
    at Parser.exports.Parser.Parser.parseString (/var/silkcloud/genesis-activation-ui/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/var/silkcloud/genesis-activation-ui/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/var/silkcloud/genesis-activation-ui/node_modules/xml2js/lib/parser.js:369:19)
    at /var/silkcloud/genesis-activation-ui/node_modules/koa-xml-body/lib/xml-parser.js:10:9
    at new Promise (&lt;anonymous&gt;)
    at convertXml2Json (/var/silkcloud/genesis-activation-ui/node_modules/koa-xml-body/lib/xml-parser.js:9:12)
    at /var/silkcloud/genesis-activation-ui/node_modules/koa-xml-body/lib/xml-parser.js:28:20
    at runMicrotasks (&lt;anonymous&gt;)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
        </code>
      </pre>
    </div>
  </body>
</html>

**Comment by dblarons** [comment] 2021-05-18 17:21
Hi, is there any resolution for this? Currently blocking us

**Comment by blockcarl** [comment] 2021-05-18 18:40
Seems like it's working now!

EDIT: Nevermind, it seems to work 1 out of 5 builds or so

**Comment by kuler90** [comment] 2021-05-19 18:42
Hi all,

I ran some tests yesterday. Locally personal activation worked fine, but on the github it started producing strange errors. I need add debug output to the action with screenshots and html pages for personal activation. I'll try to make time on the weekend.

**Comment by blockcarl** [comment] 2021-05-27 22:37
Any update on this?

**Comment by blockcarl** [comment] 2021-10-19 22:08
I am still having issues with this. A fix for this would be very helpful.

**Comment by dblarons** [comment] 2021-10-21 14:34
Hi @kuler90 — I work with @blockcarl. Our build pipeline relies on this plugin and yesterday, for whatever reason, we were hitting this issue the whole day and had to resort to building by hand on a local computer. I'm sure you are very busy, so if it would be helpful for you, perhaps you could give us some guidance on how you setup a test env for this project so that we can debug and submit a PR on our end.

**Comment by kuler90** [comment] 2021-10-21 17:14
Hi @dblarons,

Sorry, I constantly have no time to further explore this issue. You can debug personal activation locally. You just need Node.js installed. Then download repository and install dependencies by running `npm install` from repository folder. To test activation fill constants in test.js file and run it (`node src/test.js`). This script runs without headless mode for browser, you will see how the browser opens and process pages. The problem is that when I tested locally all works fine. Maybe Unity added something to prevent automatic activation from Github servers :). To investigate the problem on Github runners we need to add code to save a screenshot for every activation step and then save that screenshots to job artifacts.

**Comment by Josephksa** [comment] 2021-11-22 13:53
Same, getting error with and without unity-authenticator-key

**Closed as completed** 2022-01-25 11:13 UTC
